-- Migration: Create seasons table
-- 12-week training blocks generated by GENESIS

CREATE TABLE public.seasons (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,

  name TEXT NOT NULL, -- "Season 1", "Transformacion Q1", etc.
  number INTEGER NOT NULL, -- 1, 2, 3...

  goal TEXT NOT NULL,
  focus_areas TEXT[],

  -- Phases (each ~4 weeks)
  current_phase TEXT CHECK (current_phase IN ('foundation', 'construction', 'optimization')) DEFAULT 'foundation',
  current_week INTEGER DEFAULT 1 CHECK (current_week BETWEEN 1 AND 12),

  -- Status
  status TEXT CHECK (status IN ('active', 'completed', 'paused')) DEFAULT 'active',

  -- Dates
  start_date DATE NOT NULL,
  target_end_date DATE,
  actual_end_date DATE,

  -- Generated by GENESIS
  generated_plan JSONB, -- Full season structure

  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS Policies
ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own seasons"
  ON public.seasons FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can update own seasons"
  ON public.seasons FOR UPDATE
  USING (auth.uid() = user_id);

-- Trigger for updated_at
CREATE TRIGGER seasons_updated_at
  BEFORE UPDATE ON public.seasons
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

-- Indexes
CREATE INDEX seasons_user_id_idx ON public.seasons(user_id);
CREATE INDEX seasons_status_idx ON public.seasons(status);
